# Generated by Django 3.1 on 2020-08-26 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200825_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
